collective/collective.solr

CHANGES.rst
src/collective/solr/dispatcher.py

This allows using solr seaarch in a contextless ajax request

Add a context to queryUtility

---

src/collective/solr/browser/searchbox.pt

Translation of the Search Box label fixed.
Attribute value deleted. Plone 5 do not render the Search Box with it.

Translation & Rendering in Plone 5 Fix

---

setup.py

Not only because plone.org/products will die soon, but also because it's so useful to have this URL show up on pypi.

Link to github

---

setup.py

Is there any real need to have p.a.testing available while on production? Seems an error to me.

Move p.a.testing to testing dependencies

---

docs/CHANGES.rst
src/collective/solr/mangler.py
src/collective/solr/solr.py
src/collective/solr/tests/test_mangler.py
src/collective/solr/tests/test_solr.py
src/collective/solr/tests/utils.py

With this enhancement it's possible to select another request handler than the default /select handler for search queries using the `request_handler` parameter.
This is e.g. useful for the livesearch where an optimized request handler provides much more speed than the default one.

Add support for using different request handlers in search requests.

---

docs/CHANGES.rst
setup.py
src/collective/solr/commands.py

This adds a zopectl.command entry point for reindexing Solr. I needed this because when calling @@solr-maintenance/reindex in the browser, reindexing stopped after ~ 7500 documents, with still ~90000 documents to go. I guess it is the browser that eventually closes the connection.
The PR also fixes a problem in _get_site with recent Zope versions (args has changed).

Add zopectl.command for reindexing

---

src/collective/solr/indexer.py
src/collective/solr/solr.py
src/collective/solr/tests/data/commit_request_no_wait.txt
src/collective/solr/tests/test_solr.py

It's been long deprecated (since Solr 1.4 - November 2009),
it has been finally removed on Solr 4.0 - October 2014).
Source http://wiki.apache.org/solr/UpdateXmlMessages#Optional_attributes_for_.22commit.22_and_.22optimize.22
Release dates: https://en.wikipedia.org/wiki/Apache_Solr
While working with Solr locally I stumbled over this traceback: https://github.com/silverstripe-labs/silverstripe-fulltextsearch/issues/34 and seems that that parameter is long gone.
Was there any previous discussion about the removal of it? Nobody stumbled upon it?

Remove waitFlush

---

docs/CHANGES.rst
docs/features/atomic_updates.rst
docs/features/index.rst
solr.cfg
src/collective/solr/browser/maintenance.py
src/collective/solr/configlet.py
src/collective/solr/exceptions.py
src/collective/solr/exportimport.py
src/collective/solr/indexer.py
src/collective/solr/interfaces.py
src/collective/solr/manager.py
src/collective/solr/profiles/default/solr.xml
src/collective/solr/solr.py
src/collective/solr/tests/configlet.txt
src/collective/solr/tests/data/add_request.txt
src/collective/solr/tests/data/add_request_with_boost_values.txt
src/collective/solr/tests/data/add_response.txt
src/collective/solr/tests/data/dummy_response.txt
src/collective/solr/tests/test_exportimport.py
src/collective/solr/tests/test_indexer.py
src/collective/solr/tests/test_integration.py
src/collective/solr/tests/test_server.py
src/collective/solr/tests/test_solr.py

This is a followup of #80.
Issue with #80:
I'm unable to get a proper solrconfig.xml generated by c.r.solrinstance 5.x, which supports <updateLog/> for the atomic update feature.
So I went ahead using collective.receipe.solrinstance 6.0.0b3.
Issue with the current build:
To boost a document or index on add no longer works. 
I don't know really why, the request sent so solr contains the <doc boost="100".... But solr seems to ignore it. Any suggestions how to solve this?
**UPDATE:**
Since the AtomicUpdates and index time boosting does not work together (at least in solr 4.10.x), I implemented a new config option for the solr control panel atomic_updates. It's enabled by default.
Further I extended the docs with some important infos about the AtomicUpdate feature.
**UPDATE 2:**
Tests are now …

Implement atomic updates

---

docs/CHANGES.rst
src/collective/solr/queryparser.py
src/collective/solr/search.py

There's no benefit of having the function defined inline,
it just clutters the, already long, buildQueryAndParameters method.

Move inline function to global scope

---

docs/CHANGES.rst
src/collective/solr/browser/maintenance.py
src/collective/solr/solr.py

Allow data to be saved and ready to be used by Solr.
Note that at the end of reindex a hard commit is done which will save
the changes on the disk.
See:
http://wiki.apache.org/solr/UpdateXmlMessages#A.22commit.22_and_.22optimize.22
The idea is that if you are running a reindex to have something on Solr *while* the reindex is already going on, this way a reindex that takes several hours (+7 or 8) does not need to be be in maintenance mode (as no results will  be displayed on the search view as soon as you enable c.solr).
I still need to create a test and a changelog entry. But comments welcome.

Soft commit on reindexes

---

src/collective/solr/testing.py

Base fixtures are started before the parent and are not able to pick up the settings. This also fixes problems when testing Solr multi core setups.

Do not use SolrLayer as a base fixture.

---

setup.py

``plone.recipe.zope2instance.ctl`` and ``zopectl.command`` provide totally different arguments to the entry point methods.
I thought I had tried it, but p.r.z2instance provides something completely different than zopectl.command :-/

Revert back to zopectl.command

---

src/collective/solr/mangler.py

ZCatalog accepts ranges defined as ``min:max`` as well as ``minmax``.

Allow range minmax

---

src/collective/solr/exportimport.py
src/collective/solr/tests/test_exportimport.py

It was appending them to facets setting.
It was broken since 2012 (https://github.com/collective/collective.solr/commit/4228c98ea8ea51d3efad1e81818a97efb0329f4e) but nobody noticed :-)

Fix field-list export

---

src/collective/solr/skins/solr_site_search/livesearch_reply.py
src/collective/solr/tests/test_utils.py
src/collective/solr/utils.py

When entering multiple search terms into the live search field, they are joined together with " AND ". Later in the process, everything is lowercased, including the "AND". Thus, Solr no longer recognizes it as a boolean operator but as an additional search term.

Make suggest search work when entering multiple search terms 

---

CHANGES.rst
src/collective/solr/browser/maintenance.py
src/collective/solr/commands.py
src/collective/solr/tests/test_server.py

Reindexing the entire Solr index currently aborts if an exception is encountered.
Propagating exceptions imho is fine when indexing a single object, but when (re)indexing the whole database it should be possible to ignore exceptions. `portal_catalog` 'Clear and Rebuild' also ignores exceptions and I think c.solr should behave in the same way if just for consistency.
This PR adds a new flag 'ignore_exceptions' to browser.maintenance.reindex(). The behaviour of `@@solr-maintenance/reindex` remains unchanged, but ignoring exceptions becomes the default when using `bin/instance solr_reindex`.

Ignore exceptions when reindexing Solr

---

CHANGES.rst
src/collective/solr/indexer.py
src/collective/solr/tests/test_server.py

With the plone catalog the following works as expected:
```
obj.reindexObject(idxs=['path'])
``` 
But the solr integration filtered the `path` attribute before reindexing, since there's no equivalent solr index. 
This change extends the indexed attributes with the path relevant solr indexes `path_string`, `path_parents` and `path_depth`

Implement reindexing the path indexes in solr [5.x].

---

CHANGES.rst
src/collective/solr/profiles/default/metadata.xml
src/collective/solr/setuphandlers.py
src/collective/solr/upgrades.zcml

Otherwise you get KeyError: `collective.solr.facets` in the search viewlet.
And on the control panel you get another KeyError: 'Interface `collective.solr.interfaces.ISolrSchema` defines a field `index_timeout`, for which there is no record.'
We remove the old config utility in this step, because the object is broken.
See https://github.com/collective/collective.solr/issues/155

Added upgrade step for registry when upgrading from 5.0.3.

---

CHANGES.rst
solr.cfg

The config was hardcoding the JMX (Java Management Extensions) host and port. Now it is clearer that you can configure them.
Mostly, I found it strange that there was a `solr-port` setting and we were completely ignoring that in the `java_opts` and instead used hardcoded port 8984. To me this gave the impression that this port 8984 was only used at build time to maybe set a default, and that `solr-instance fg` would just use the port from the settings and port 8984 would never be used.
Initially I changed that to use the same settings, with `${:host}` and `${:port}`.
That seems to work fine, and we could also use that to keep things simple.
But probably it is better to keep the ports separate.
I did not know JMX, but you can start `jconsole` and connect to your Solr instance and see some …

solr.cfg: configure JMX host and port separately.

---

CHANGES.rst
src/collective/solr/tests/test_browser_suggest.py

Tests for the 5.x branch are currently failing.
This PR fixes the tests for the 5.x branch.

Use unittest instead unittest2 in test_browser_suggest.py to fix tests.

---

CHANGES.rst
src/collective/solr/indexer.py
src/collective/solr/solr.py
src/collective/solr/tests/data/schema.xml
src/collective/solr/tests/test_indexer.py
src/collective/solr/tests/test_parser.py
src/collective/solr/tests/test_server.py

This PR fixes the issue where indexes can be removed with an atomic-update.
Sending the following xml to the solr will update the Description-index of the object with UID xxx with the string "Example"
```
<add><doc><field name="UID">xxx</field><field name="Description" update="set">Example</field></doc></add>
```
Sending the following xml to the solr will update the searchwords-index of the object with UID yyy with a list with an empty string: [""]
```
<add><doc><field name="UID">yyy</field><field name="searchwords" update="set"></field></doc></add>
```
Sending the following xml to the solr will remove all indexes of the object with the UID zzz
```
<add><doc><field name="UID">zzz</field></doc></add>
```
So the last request would be bad. We have two different cases where this request will …

Fix: Indexing with atomic-update can remove all other attributes from the index.

---

CHANGES.rst
src/collective/solr/search.py

Fixes UnicodeDecodeError when searching for non-ascii text

Handle non-ascii values in the query.

---

CHANGES.rst
requirements.txt
setup.py
src/collective/solr/tests/test_server.py
versions.cfg

collective.indexing was not pinned to a specific version and the last version was breaking a test, which is partially redundant now.

Fix master

---

.travis.yml
CHANGES.rst
requirements.txt
src/collective/solr/search.py
src/collective/solr/tests/test_server.py
src/collective/solr/utils.py
versions.cfg

Allow multiple Plone instances in one Zope app

---

src/collective/solr/browser/searchbox.pt

With Products.CMFPlone 4.3.17, in Products/CMFPlone/skins/plone_ecmascript/livesearch.js
The livesearch fails due to the action that does not match (search instead of @@search).
Anyhow using view without @@ can conflict with objects ids.

Fix livesearch on Plone 4.3

---

CHANGES.rst
src/collective/solr/configure.zcml
src/collective/solr/profiles/default/types/Collection.xml
src/collective/solr/profiles/default/types/Document.xml
src/collective/solr/profiles/default/types/Event.xml
src/collective/solr/profiles/default/types/File.xml
src/collective/solr/profiles/default/types/Folder.xml
src/collective/solr/profiles/default/types/Image.xml
src/collective/solr/profiles/default/types/Link.xml
src/collective/solr/profiles/default/types/News_Item.xml

...instead of "collective.solr.behaviors.ISolrFields".
Using the full dotted behavior path leads to a hellish amount of "could not adapt" errors in all our Plone 5.2 projects.
Without this fix collective.solr is unusable in production with Plone 5.2/Python3.

Use named behavior "solr.fields".

---

CHANGES.rst
plone-5.1.x.cfg
src/collective/solr/solr.py
src/collective/solr/tests/test_subjects.py

Without any modification this test produces the following error:
```
Error in test test_umlauts (collective.solr.tests.test_subjects.TestDublincoreSubjectField)
Traceback (most recent call last):
File "/path/to/python/parts/opt/lib/python2.7/unittest/case.py", line 329, in run
testMethod()
File "/path/to/pkgs/collective.solr/src/collective/solr/tests/test_subjects.py", line 27, in test_umlauts
transaction.commit()
File "/path/to/dotfiles/.buildout/eggs/transaction-2.4.0-py2.7.egg/transaction/_manager.py", line 252, in commit
return self.manager.commit()
File "/path/to/dotfiles/.buildout/eggs/transaction-2.4.0-py2.7.egg/transaction/_manager.py", line 131, in commit
return self.get().commit()
File "/path/to/dotfiles/.buildout/eggs/transaction-2.4.0-py2.7.egg/transaction/_transaction.py", …
```

Fix index subjects with non-ascii characters.

---

CHANGES.rst
src/collective/solr/indexer.py

Newer Solr versions expect json so we have to set wt=xml in the BinaryAdder.

Fix BinaryAdder for Tika.

---

src/collective/solr/mangler.py
src/collective/solr/search.py
src/collective/solr/tests/test_query.py

This branch add the support for "not" queries introduced in Products.ZCatalog 3.0a1

Add support for "not" queries

---

CHANGES.rst
src/collective/solr/parser.py
src/collective/solr/tests/test_parser.py

This solve an issue with plone.app.querystring
https://github.com/plone/plone.app.querystring/blob/master/plone/app/querystring/querybuilder.py#L173

Correctly implement `actual_result_count` property setter

---

CHANGES.rst
src/collective/solr/mangler.py
src/collective/solr/tests/test_mangler.py

This solve an issue with plone.app.events portlet that use python datetime in queries.

Correctly handle queries with python `date` or `datetime` objects

---

CHANGES.rst
src/collective/solr/utils.py

This happen when using SolR for all queries and defining "getObjPositionInParent" as an integer index, the indexer fails due to some contents that does not have a value for this index.

Fix `getObjPositionInParent` index by avoiding indexing null values

---

CHANGES.rst
src/collective/solr/indexer.py
src/collective/solr/tests/test_indexer.py

I had an issue in plone 4 where some dates were weirdly formatted in strformat.
This happens when the millisecond are too close to 0 or 1000. Then its faultly rounded and solr doesn't like a date like this : 2015-07-20T11:07:60.000Z (instead of 2015-07-20T11:07:59.999Z)
For this example I had this in the indexer : 
```
71         if isinstance(value, DateTime):
72             v = value.toZone("UTC")
73  ->         value = "%04d-%02d-%02dT%02d:%02d:%06.3fZ" % (
74                 v.year(),
75                 v.month(),
76                 v.day(),
77                 v.hour(),
78                 v.minute(),
(ipdb>) v.second()
59.99973
(ipdb>) "%06.3f" % v.second()
'60.000'
```

Fix millisecond management while indexing dates

---

CHANGES.rst
src/collective/solr/tests/test_server.py
src/collective/solr/utils.py

Fixes "AssertionError: term is not a simple search" with certain characters.
Also fix tests

Remove all conflicting characters from forced simple search

---

src/collective/solr/contentlisting.py
src/collective/solr/tests/test_contentlisting.py

Replicate the behavior of p.a.contentlisting.catalog.CatalogContentListingObject
to allow access to other stored data

Contentlisting: lookup unknown data

---

CHANGES.rst
src/collective/solr/dispatcher.py
src/collective/solr/manager.py
src/collective/solr/mangler.py
src/collective/solr/search.py
src/collective/solr/tests/test_multicore.py

This PR add a new parameter `core` for SolR search that can be used to search on other SolR core from the same SoLR server.
To allow a search from a new SolR core, a new named utility must be defined for ISolrConnectionManager with the core id as name.

Allow search accross multiple core

---

.github/workflows/black.yml
CHANGES.rst
Makefile
src/collective/solr/exceptions.py
src/collective/solr/manager.py
src/collective/solr/solr.py

This error connection happens randomly and breaks a thread connection
permanently.
```
o.a.s.s.SolrRequestParsers Couldn't get multipart parts in order to
delete them => java.io.IOException: Missing initial multi part boundary
at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:606)
java.io.IOException: Missing initial multi part boundary
```
The fix resets the connection and completely recreates it from within
the manager. (A simple connection reset is not sufficient.)
There is no evidence of what causes the issue but a reindex with many
content items breaks the connection of the thread that was doing the
reindex in a reliable way. This solution fixes this scenario.

Fix multipart error on search

---

CHANGES.rst
src/collective/solr/browser/maintenance.py
src/collective/solr/interfaces.py
src/collective/solr/mangler.py
src/collective/solr/search.py
src/collective/solr/solr.py
src/collective/solr/tests/test_mangler.py
src/collective/solr/tests/test_server.py

…er exceeds a certain value. This fixes #357

Avoid java.lang.NumberFormatException in Solr when the 'rows' parameter

---

CHANGES.rst
src/collective/solr/indexer.py
src/collective/solr/tests/test_indexer.py

Set value should be handled in the same way as list or tuple values. This fixes indexing for multivalue fields which serialize as sets.
Also retro-add some tests for tuple and list values.

Fix indexing of set values in multivalue fields

---

CHANGES.rst
src/collective/solr/tests/test_query.py
src/collective/solr/tests/test_utils.py
src/collective/solr/utils.py

Fix the problem and make "foo **" result in the same query as "foo". Without the fix this used to cause an 500 Internal Server Error.
One might argue that "foo **"  is not a valid query, to start with. However it can be expected as an input, thus it should not cause a cryptic error anyway. The fix causes to yield the expected results by stripping out the standalone wildcard.

Strip standalone wildcards from the searchable text (#362)

---

src/collective/solr/interfaces.py
src/collective/solr/mangler.py
src/collective/solr/profiles/default/registry.xml
src/collective/solr/stopword.py
src/collective/solr/testing.py
src/collective/solr/tests/test_mangler.py
src/collective/solr/tests/test_stopwords.py

- add stopwords to registry
- support function for getting the stopwords
- cache to optimize the parsing of stopwords.txt
This transforms the (term AND term*) expression for stopwords, removing the wildcard expression. Such an expression would never match any documents, because solr won't remove the wildcard term, but the  stopword will be missing from the index. This workaround does that with no side effects, as stopwords would be ignored by solr anyway.

Prevent wildcard expressions for stopwords in simple expressions

---

CHANGES.rst
src/collective/solr/solr.py
src/collective/solr/tests/data/add_request_with_none.txt
src/collective/solr/tests/data/add_request_with_none_and_boost_value.txt
src/collective/solr/tests/test_solr.py

This is very surprising, but it looks like solr lacked the support for missing (None) values, so they got degraded to a "None" string. This PR adds the condition that fixes it.
Supporting None values was already added earlier for lists (multi values), but not for the simple index use case.

Fix indexing of null values

---

CHANGES.rst
src/collective/solr/stopword.py
src/collective/solr/tests/test_stopwords.py

The stopwords.txt does not allow leading spaces, but the registry pads it up because of the way we define it in the xml.

Allow leading spaces in the stopwords configuration
