CHANGES.rst, src/collective/solr/browser/suggest.py, src/collective/solr/solr.py, src/collective/solr/tests/test_browser_suggest.py
We need to make a GET request and use the 'word' key.
=> fixed suggest-terms request method

src/collective/solr/browser/typeahead.pt
Fixed syntax error in javascript
=> Disabled default browser autocomplete

docs/index.rst
I think that's a recommended guideline from Plone documentation right? @svx
=> Remove badges from docs

docs/CHANGES.rst, src/collective/solr/dispatcher.py, src/collective/solr/exceptions.py, src/collective/solr/indexer.py, src/collective/solr/solr.py, src/collective/solr/tests/test_facets.py
Fixes:
https://github.com/collective/collective.solr/issues/106
=> Unify all exceptions raised

setup.py
This way one can see them when doing 'bin/instance help' and 'bin/instance help solr_reindex'
=> Add command scripts for p.r.zope2instance

.gitignore, src/collective/solr/testing.py
This does not work if SolrLayer is used outside of c.solr.
=> WIP: Fix buildout bin dir directory lookup.

CHANGES.rst, setup.py, src/collective/solr/dispatcher.py, src/collective/solr/indexer.py, src/collective/solr/profiles/default/componentregistry.xml
- Make extracting text from binary content and indexing 2 steps (#65) -> obsoletes PR #122 
- Fix indexing of new files (#120) -> obsoletes PR #121
=> Combinded PR for #121 and #122 because of testing interdependencies

src/collective/solr/manager.py, src/collective/solr/tests/errors.txt
Seems that what was causing the test isolation has been fixed already.
=> Uncoment test

README.rst
If all indexes that are using a given lexicon are removed, the lexicon itself could be removed as well.
=> Add a note about removing lexicons

CHANGES.rst, src/collective/solr/indexer.py, src/collective/solr/tests/test_server.py
Cherry-picked the changes made for `5.x` branch.
Check #152 for details.
=> Implement reindexing the path indexes in solr [master].

README.rst, docs/base/indexing.rst, docs/usage/install.rst, solr-5.0.x.cfg, solr-5.1.x.cfg, solr-5.2.x.cfg, src/collective/solr/interfaces.py, src/collective/solr/locales/de/LC_MESSAGES/solr.po, src/collective/solr/locales/en/LC_MESSAGES/solr.po, src/collective/solr/locales/it/LC_MESSAGES/solr.po, src/collective/solr/locales/nl/LC_MESSAGES/solr.po, src/collective/solr/locales/solr.pot
Mostly:
- fixed typos
- warn about Solr 5, especially 5.2.
=> Various documentation/config improvements.

CHANGES.rst, src/collective/solr/browser/controlpanel.pt
And added titles to all four maintenance links that briefly explain what they do.
=> Added link to Solr sync in our control panel.

CHANGES.rst, setup.py, src/collective/solr/behaviors.py, src/collective/solr/browser/p4_search.py, src/collective/solr/configure.zcml, src/collective/solr/extender.zcml, src/collective/solr/interfaces.py, src/collective/solr/locales/de/LC_MESSAGES/solr.po, src/collective/solr/locales/en/LC_MESSAGES/solr.po, src/collective/solr/locales/it/LC_MESSAGES/solr.po, src/collective/solr/locales/nl/LC_MESSAGES/solr.po, src/collective/solr/locales/solr.pot, src/collective/solr/tests/test_behavior.py, src/collective/solr/tests/test_linguaplone.py, src/collective/solr/tests/test_utils.py
=> Add behavior and german translation

src/collective/solr/indexer.py
=> fix #202 (xml parsing exceptions do not abort full reindex)

plone-4.3.x.cfg, plone-5.1.x.cfg, plone-5.2.x.cfg
Test against the latest released versions
=> Bump plone versions

CHANGES.rst, src/collective/solr/indexer.py, src/collective/solr/tests/test_indexer.py, src/collective/solr/tests/test_utils.py, src/collective/solr/utils.py
Fixes:
https://github.com/collective/collective.solr/issues/96
=> Index comments

src/collective/solr/indexer.py, src/collective/solr/tests/test_indexer.py, src/collective/solr/tests/test_utils.py, src/collective/solr/utils.py
Reverts collective/collective.solr#102
=> Revert "Index comments"

src/collective/solr/monkey.py
=> Conditionally patch Lazy

.travis.yml, CHANGES.rst, setup.py, src/collective/solr/browser/controlpanel.py, src/collective/solr/browser/maintenance.py, src/collective/solr/indexer.py, src/collective/solr/tests/test_query.py, src/collective/solr/tests/test_server.py, versions.cfg
=> Initial support for Python3.8

src/collective/solr/solr.py
Fixes https://github.com/collective/collective.solr/issues/287
=> Clean previous filled list-field in solr if indexer returns empty list.

CHANGES.rst, docs/usage/config.rst, src/collective/solr/manager.py, src/collective/solr/tests/test_server.py
This is very helpful for Plone deployed with Docker.
This PR should be merged after #310
=> Allow using of environment variables for SolR config

README.rst
resolve https://github.com/collective/collective.solr/issues/330
=> update pypi links

docs/usage/solrcloud.rst
resolve https://github.com/collective/collective.solr/issues/332
=> update SolrCloud link

docs/usage/monitoring.rst
resolve https://github.com/collective/collective.solr/issues/334
=> update SolrJmx link

CHANGES.rst, src/collective/solr/contentlisting.py
=> Fix handling of image_scales

CHANGES.rst, src/collective/solr/profiles/default/metadata.xml, src/collective/solr/setuphandlers.py, src/collective/solr/upgrades.zcml
=> fix: add upgrade step for missing stopwords registry entries

CHANGES.rst, src/collective/solr/utils.py
=> Fix creating a fresh site in Plone 6.1 when registry does not exist yes
